"use client";

import { useState } from "react";
import { FileDown, Loader2 } from "lucide-react";
import { API_BASE_URL } from "@/lib/api";
import { useTenant } from "@/contexts/TenantContext";

interface PDFExportProps {
  startDate: string;
  endDate: string;
  variant?: "button" | "icon";
}

export default function PDFExport({ startDate, endDate, variant = "button" }: PDFExportProps) {
  const { tenant } = useTenant();
  const [exporting, setExporting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  async function exportPDF() {
    setExporting(true);
    setError(null);
    
    try {
      // Fetch P&L data
      const params = new URLSearchParams({
        org_id: tenant.org_id,
        location_id: tenant.location_id,
        start_date: startDate,
        end_date: endDate,
      });
      
      const res = await fetch(`${API_BASE_URL}/api/v1/reports/profit-loss?${params}`);
      
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.detail || "Failed to fetch P&L data");
      }
      
      const data = (await res.json()) as { revenue?: number; expenses?: number };
      
      // Generate PDF client-side using html2canvas + jsPDF
      await generatePDFFromData(data);
      
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Export failed");
      setTimeout(() => setError(null), 3000);
    } finally {
      setExporting(false);
    }
  }
  
  async function generatePDFFromData(data: { revenue?: number; expenses?: number }) {
    // Dynamic import to reduce bundle size
    const { default: jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;
    
    // Header
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Profit & Loss Statement", pageWidth / 2, y, { align: "center" });
    
    y += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Period: ${startDate} to ${endDate}`, pageWidth / 2, y, { align: "center" });
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y + 5, { align: "center" });
    
    y += 20;
    
    // Revenue Section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Revenue", 20, y);
    y += 7;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    const revenue = data.revenue || 0;
    doc.text(`Total Revenue:`, 25, y);
    doc.text(`₹${revenue.toLocaleString("en-IN")}`, pageWidth - 25, y, { align: "right" });
    y += 10;
    
    // Expenses Section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Expenses", 20, y);
    y += 7;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    const expenses = data.expenses || 0;
    doc.text(`Total Expenses:`, 25, y);
    doc.text(`₹${expenses.toLocaleString("en-IN")}`, pageWidth - 25, y, { align: "right" });
    y += 10;
    
    // Gross Profit
    y += 5;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, y, pageWidth - 20, y);
    y += 7;
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    const grossProfit = revenue - expenses;
    doc.text(`Gross Profit:`, 20, y);
    doc.text(`₹${grossProfit.toLocaleString("en-IN")}`, pageWidth - 25, y, { align: "right" });
    y += 10;
    
    // Tax
    const taxRate = 0.18; // 18% GST
    const tax = grossProfit * taxRate;
    doc.setFont("helvetica", "normal");
    doc.text(`Tax (18%):`, 25, y);
    doc.text(`₹${tax.toLocaleString("en-IN")}`, pageWidth - 25, y, { align: "right" });
    y += 10;
    
    // Net Profit
    y += 5;
    doc.line(20, y, pageWidth - 20, y);
    y += 7;
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const netProfit = grossProfit - tax;
    doc.text(`Net Profit:`, 20, y);
    doc.text(`₹${netProfit.toLocaleString("en-IN")}`, pageWidth - 25, y, { align: "right" });
    
    // Footer
    y = doc.internal.pageSize.getHeight() - 20;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by TITAN ERP | Ever Built", pageWidth / 2, y, { align: "center" });
    
    // Save
    const filename = `PL_${startDate}_${endDate}_${Date.now()}.pdf`;
    doc.save(filename);
  }
  
  if (variant === "icon") {
    return (
      <button
        onClick={exportPDF}
        disabled={exporting}
        className="rounded-lg border border-white/10 bg-white/5 p-2 text-zinc-300 transition hover:bg-white/10 disabled:opacity-60"
        title="Export PDF"
      >
        {exporting ? (
          <Loader2 size={16} className="animate-spin" />
        ) : (
          <FileDown size={16} />
        )}
      </button>
    );
  }
  
  return (
    <button
      onClick={exportPDF}
      disabled={exporting}
      className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-purple-400 to-pink-400 px-4 py-2 text-sm font-semibold text-black shadow-lg transition hover:scale-[1.02] disabled:opacity-60"
    >
      {exporting ? (
        <>
          <Loader2 size={16} className="animate-spin" />
          Generating PDF...
        </>
      ) : (
        <>
          <FileDown size={16} />
          Export P&L PDF
        </>
      )}
    </button>
  );
}
